### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by DreamXzxy** [AztecProtocol/aztec-ganache-starter-kit#31]
When I tried to run the demo following README.MD, the console reported an error.
![image](https://user-images.githubusercontent.com/17998878/73654157-f15b1000-46c5-11ea-8beb-557b2b880cbf.png)

**Comment by thomas-waite** [comment]
Hi @DreamXzxy , thanks for flagging this. The error you've posted is related to our SDK - we've  pushed a fix so it should now be all good. Let me know that this works for you.  

As an aside, this particular starter kit is meant to demonstrate how to use the low level AZTEC proof construction package `aztec.js` along with the relevant contracts from the`protocol` package. 

It looks like you're instead importing the SDK and trying that out here? The best places to try out the SDK would be in our interactive docs: https://docs.aztecprotocol.com/#/SDK/Getting%20started or in this starter kit: https://github.com/AztecProtocol/sdk-starter-kit 

Would be happy to answer any further questions you have!

**Comment by thomas-waite** [comment]
I'm going to close this issue now @DreamXzxy - we've pushed a fix to the SDK that deals with this. Thanks again for raising it and feel free to reach out if you encounter any further bugs
