### ISSUE TITLE
ganache dont start

### ISSUE THREAD

**Issue by salilalla** [AztecProtocol/aztec-ganache-starter-kit#6]
i m having this issue ,ganache dont start ?

aztec-ganache-starter-kit-master>npm start

> aztec-ganache-starter-kit@1.0.0 start C:\Users\AER25\Documents\AZTEC GANACHE\aztec-ganache-starter-kit-master
> npm run ganache

> aztec-ganache-starter-kit@1.0.0 ganache C:\Users\AER25\Documents\AZTEC GANACHE\aztec-ganache-starter-kit-master
> babel-node scripts/run ganache

Start Running 'ganache'...

 Error: spawn ganache-cli ENOENT

Child process exited with code -4058

Finished 'ganache' in 100 ms

**Comment by thomas-waite** [comment]
Thanks for raising @salilalla , I'll take a look at this today

**Comment by thomas-waite** [comment]
Hey, so I'm able to reproduce the same error as you if I don't have `ganache-cli` installed. Could you double check that you ran `yarn install` or `npm install` before you ran `npm run ganache`? If not, then please run that and give it another go. 

If that doesn't work, could you remove the installed `node_modules`, then reinstall and give `npm run ganache` another go. 

Let me know if that works goes :)

**Comment by thomas-waite** [comment]
Hey @salilalla I'm going to close this issue now. If you still have problems after trying the steps above, then feel free to reopen the issue and I'll be happy to lend a hand!
